---
# file: roles/kubernetes/tasks/main.yml
- name: Disable swap
  become: yes
  shell: swapoff -a

- name: Remove swapfile from /etc/fstab
  become: yes
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Install Kubernetes
  import_tasks: "install.yml"
  when: "'kubernetes' not in ansible_facts.packages"

- name: Configure master node
  block:
    - name: Fetch kubeadm images
      shell: kubeadm config images pull

    - name: Init master node
      become: yes
      shell: "kubeadm init \
        --pod-network-cidr={{ cluster_network }} \
        --apiserver-advertise-address={{ ansible_ssh_host }} \
        --apiserver-cert-extra-sans={{ ansible_ssh_host }} > .cluster_init"
      args:
        chdir: "{{ home_dir }}"
        creates: .cluster_init

    - name: Create .kube directory
      file:
        path: "{{ home_dir }}/.kube"
        state: directory
        mode: 0755

    - name: Copy admin.conf to user's kube config
      become: yes
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ home_dir }}/.kube/config"
        owner: ansible
        group: ansible
        mode: 0755
        remote_src: yes

    - name: Copy flannel kubernetes configuration
      copy:
        src: kube-flannel.yml
        dest: "{{ home_dir }}/kube-flannel.yml"
        owner: ansible
        group: ansible
        mode: 0644

    - name: Configure network
      shell: "kubectl apply -f {{ home_dir }}/kube-flannel.yml > .network_init"
      args:
        chdir: "{{ home_dir }}"
        creates: .network_init

    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

  when: "'master' in group_names"

- name: Worker nodes join cluster
  become: yes
  shell: "{{ hostvars['master'].join_command }} >> .node_joined"
  args:
    chdir: "{{ home_dir }}"
    creates: .node_joined
  when: "'workers' in group_names"
